a=[['Rani Mukerji', 'Rohit Saraf'],
 ['Kanu Bannerjee', 'Karuna Bannerjee'],
 ['Mohanlal', 'Meena'],
 ['Amol Palekar', 'Bindiya Goswami'],
 ['Kamal Haasan', 'Saranya Ponvannan'],
 ['Kamal Haasan', 'Madhavan'],
 ['Soumitra Chatterjee', 'Sharmila Tagore'],
 ['Nana Patekar', 'Medha Manjrekar'],
 ['Mohanlal', 'Thilakan'],
 ['Kathir', 'Anandhi'],
 ['Kay Kay Menon', 'Pawan Malhotra'],
 ['Mohanlal', 'Shobana'],
 ['Kamal Haasan', 'Shivaji Ganesan'],
 ['Vishnu Vishal', 'Amala Paul'],
 ['Vijay Sethupathi', 'Trisha Krishnan'],
 ['Shane Nigam', 'Soubin Shahir'],
 ['Aamir Khan', 'Madhavan'],
 ['Darsheel Safary', 'Aamir Khan'],
 ['Dinesh', 'Samuthirakani'],
 ['Rajinikanth', 'Mammootty'],
 ['Kamala Adhikari', 'Lalchand Banerjee'],
 ['Naseeruddin Shah', 'Ravi Baswani'],
 ['Dhanush', 'Manju Warrier'],
 ['Guru Dutt', 'Waheeda Rehman'],
 ['Dev Anand', 'Waheeda Rehman'],
 ['Rajesh Khanna', 'Amitabh Bachchan'],
 ['Madhavan', 'Simran'],
 ['Dharmendra', 'Sharmila Tagore'],
 ['Nani', 'Shraddha Srinath'],
 ['Karthi', 'Narain'],
 ['Mohanlal', 'Meena'],
 ['Jayam Ravi', 'Arvind Swamy'],
 ['Madhavan', 'Vijay Sethupathi'],
 ['Dhanush', 'Ameer Sultan'],
 ['Madhavan', 'Suriya'],
 ['Aditi Balan', 'Padmashri Mohammad Ali'],
 ['Anupam Kher', 'Boman Irani'],
 ['Mammootty', 'Sadhana'],
 ['Vijay Sethupathi', 'Fahadh Faasil'],
 ['Sohum Shah', 'Jyoti Malshe'],
 ['Keerthy Suresh', 'Dulquer Salmaan'],
 ['Naveen Polishetty', 'Shruti Sharma'],
 ['Ayushmann Khurrana', 'Tabu'],
 ['Ramesh', 'J. Vignesh'],
 ['Nivin Pauly', 'Sai Pallavi'],
 ['Rahman', 'Prakash Raghavan'],
 ['J.D. Chakravarthi', 'Manoj Bajpayee'],
 ['Rajkummar Rao', 'Prabhleen Sandhu'],
 ['Nazriya Nazim', 'Nivin Pauly'],
 ['Arjun Sarja', 'Manisha Koirala'],
 ['Vijay Sethupathi', 'Sanchita Shetty'],
 ['Vikram', 'Sada'],
 ['Kamal Haasan', 'Gautami'],
 ['Manoj Bajpayee', 'Richa Chadha'],
 ['Siddharth', 'Bobby Simha'],
 ['Farhan Akhtar', 'Sonam Kapoor'],
 ['Irrfan Khan', 'Mahie Gill'],
 ['Irrfan Khan', 'Konkona Sen Sharma'],
 ['Shah Rukh Khan', 'Gayatri Joshi'],
 ['Akshay Kumar', 'Sunil Shetty'],
 ['Sanjeev Kumar', 'Dharmendra'],
 ['Ajay Devgn', 'Shriya Saran'],
 ['Rinku Rajguru', 'Akash Thosar'],
 ['Swara Bhaskar', 'Ratna Pathak Shah'],
 ['Amitabh Bachchan', 'Rani Mukerji'],
 ['Shah Rukh Khan', 'Vidya Malvade'],
 ['Vikram', 'Suriya'],
 ['Aamir Khan', 'Ayesha Jhulka'],
 ['Soumitra Chatterjee', 'Madhabi Mukherjee'],
 ['Prithviraj Kapoor', 'Madhubala'],
 ['Dulquer Salmaan', 'Thilakan'],
 ['Aamir Khan', 'Siddharth'],
 ['Rajat Barmecha', 'Ronit Roy'],
 ['Kangana Ranaut', 'Rajkummar Rao'],
 ['Ayushmann Khurrana', 'Nassar'],
 ['Hrithik Roshan', 'Farhan Akhtar'],
 ['Anupam Kher', 'Naseeruddin Shah'],
 ['Sanjay Dutt', 'Arshad Warsi'],
 ['Aamir Khan', 'Saif Ali Khan'],
 ['Aamir Khan', 'Naseeruddin Shah'],
 ['Richa Chadha', 'Sanjay Mishra'],
 ['Aamir Khan', 'Salman Khan'],
 ['Paresh Rawal', 'Akshay Kumar'],
 ['Arvind Swamy', 'Madhoo'],
 ['Fahadh Faasil', 'Aparna Balamurali'],
 ['Aamir Khan', 'Gracy Singh'],
 ['Madhavan', 'Shalini'],
 ['Karthi', 'Rakul Preet Singh'],
 ['Vidya Balan', 'Parambrata Chattopadhyay'],
 ['Rajinikanth', 'Nagma'],
 ['Aamir Khan', 'Rajinder Sharma Nanu'],
 ['Vicky Kaushal', 'Paresh Rawal'],
 ['Shreyas Talpade', 'Naseeruddin Shah'],
 ['Taapsee Pannu', 'Amitabh Bachchan'],
 ['Ranbir Kapoor', 'Priyanka Chopra'],
 ['Sathish Neenasam', 'Sruthi Hariharan'],
 ['Ajay Devgn', 'Sushant Singh'],
 ['Siddharth', "Genelia D'Souza"],
 ['Arvind Swamy', 'Manisha Koirala'],
 ['Irrfan Khan', 'Tabu'],
 ['Ajay Devgn', 'Kareena Kapoor'],
 ['Akshaye Khanna', 'Richa Chadha'],
 ['Sanjay Dutt', 'Arshad Warsi'],
 ['Amitabh Bachchan', 'Shashi Kapoor'],
 ['Kamal Haasan', 'Sukanya'],
 ['Sushant Singh Rajput', 'Shraddha Kapoor'],
 ['Shah Rukh Khan', 'Kajol'],
 ['Prabhas', 'Rana Daggubati'],
 ['Kay Kay Menon', 'Raj Singh Chaudhary'],
 ['Sunil Dutt', 'Saira Banu'],
 ['Tabu', 'Shahid Kapoor'],
 ['Abhay Bethiganti', 'Keshav Deepak'],
 ['Nargis', 'Sunil Dutt'],
 ['Rahul Bhatt', 'Ronit Roy'],
 ['Vijay Varma', 'Nakul Roshan Sahdev'],
 ['Mahesh Babu', 'Trisha Krishnan'],
 ['Shivaji Ganesan', 'Rajinikanth'],
 ['Akshay Kumar', 'Anupam Kher'],
 ['Ram Charan', 'Samantha Ruth Prabhu'],
 ['Abhay Deol', 'Mahie Gill'],
 ['Aydah El-Kashef', 'Yogesh Shah'],
 ['Ayushmann Khurrana', 'Neena Gupta'],
 ['Chhabi Biswas', 'Sardar Akhtar'],
 ['Salman Khan', 'Harshaali Malhotra'],
 ['Sanjay Dutt', 'Namrata Shirodkar'],
 ['Kishore Kumar G.', 'Rakshit Shetty'],
 ['Ajay Devgn', 'Mohanlal'],
 ['Vijay Deverakonda', 'Shalini Pandey'],
 ['Sanjay Mishra', 'Seema Bhargava'],
 ['Vineet Kumar Singh', 'Jimmy Sheirgill'],
 ['Suriya', 'Simran'],
 ['Manoj Kumar Manchu', 'Allu Arjun'],
 ['Yash', 'Srinidhi Shetty'],
 ['Nawazuddin Siddiqui', 'Radhika Apte'],
 ['Vijay Sethupathi', 'Ramya Nambeeshan'],
 ['Shah Rukh Khan', 'Kajol'],
 ['Shah Rukh Khan', 'Preity Zinta'],
 ['Shahid Kapoor', 'Kareena Kapoor'],
 ['Sushant Singh Rajput', 'Sanjana Sanghi'],
 ['Prithviraj Sukumaran', 'Jayasurya'],
 ['Prithviraj Sukumaran', 'Sreejith Ravi'],
 ['Kamal Haasan', 'Mohanlal'],
 ['Akshay Kumar', 'Radhika Apte'],
 ['Sunny Deol', 'Sunil Shetty'],
 ['Hrithik Roshan', 'Preity Zinta'],
 ['Ayesha Takia', 'Shreyas Talpade'],
 ['Hrithik Roshan', 'Mrunal Thakur'],
 ['Suriya', 'Jyotika'],
 ['Akshay Kumar', 'Nimrat Kaur'],
 ['Kamal Haasan', 'Jyotika'],
 ['Prabhas', 'Rana Daggubati'],
 ['Dulquer Salmaan', 'Parvathy Thiruvothu'],
 ['Akshay Kumar', 'Danny Denzongpa'],
 ['Kamal Haasan', 'Shah Rukh Khan'],
 ['Sridevi', 'Adil Hussain'],
 ['Ajay Devgn', 'Gracy Singh'],
 ['Mahesh Babu', 'Bhoomika Chawla'],
 ['Irrfan Khan', 'Nimrat Kaur'],
 ['Irrfan Khan', 'Saba Qamar'],
 ['Nana Patekar', 'Revathi'],
 ['Dharmendra', 'Rimi Sen'],
 ['Akkineni Nageshwara Rao', 'Nagarjuna Akkineni'],
 ['Zaira Wasim', 'Meher Vij'],
 ['Amitabh Bachchan', 'Taapsee Pannu'],
 ['Sushant Singh Rajput', 'Bhumi Pednekar'],
 ['Alia Bhatt', 'Vicky Kaushal'],
 ['Anil Kapoor', 'Sridevi'],
 ['Anil Kapoor', 'Rani Mukerji'],
 ['Ayushmann Khurrana', 'Yami Gautam'],
 ['Mahesh Babu', "Ileana D'Cruz"],
 ['Shahid Kapoor', 'Alia Bhatt'],
 ['Amitabh Bachchan', 'Zeenat Aman'],
 ['Partho A. Gupte', 'Numaan Sheikh'],
 ['Arjun Rampal', 'Farhan Akhtar'],
 ['Nirup Bhandari', 'Radhika Narayan'],
 ['Vinay Pathak', 'Sarita Joshi'],
 ['Shah Rukh Khan', 'Preity Zinta'],
 ['Shawn Ku', 'Christy Chung'],
 ['Manoj Bajpayee', 'Rajkummar Rao'],
 ['Mithun Chakraborty', 'Abhishek Bachchan'],
 ['Allu Arjun', 'Anuradha Mehta'],
 ['Abhay Deol', 'Paresh Rawal'],
 ['Dhanush', 'Saranya Ponvannan'],
 ['Adivi Sesh', 'Sobhita Dhulipala'],
 ['Sushant Singh Rajput', 'Kiara Advani'],
 ['Paresh Rawal', 'Kay Kay Menon'],
 ['Sushant Singh Rajput', 'Rajkummar Rao'],
 ['Rishi Kapoor', 'Rajat Kapoor'],
 ['Ranbir Kapoor', 'Nargis Fakhri'],
 ['Sudeep', 'Nani'],
 ['Shah Rukh Khan', 'Suchitra Krishnamoorthi'],
 ['Juhi Chawla', 'Sunny Deol'],
 ['Rajeev Khandelwal', 'Aishwarya'],
 ['Rajkummar Rao', 'Pankaj Tripathi'],
 ['Suriya', 'Samantha Ruth Prabhu'],
 ['Aamir Khan', 'Nandita Das'],
 ['Sri Murali', 'Haripriya'],
 ['Amitabh Bachchan', 'Mithun Chakraborty'],
 ['John Abraham', 'Nargis Fakhri'],
 ['Kartik Aaryan', 'Raayo S. Bakhirta'],
 ['Sonam Kapoor', 'Shabana Azmi'],
 ['Amitabh Bachchan', 'Abhishek Bachchan'],
 ['Vinay Pathak', 'Rajat Kapoor'],
 ['Shweta Basu Prasad', 'Mithun Chakraborty'],
 ['Joseph Vijay', 'Kajal Aggarwal'],
 ['Alia Bhatt', 'Randeep Hooda'],
 ['Sushant Singh Rajput', 'Anand Tiwari'],
 ['Ram Charan', 'Kajal Aggarwal'],
 ['Abhay Deol', 'Gul Panag'],
 ['Shah Rukh Khan', 'Kajol'],
 ['Kangana Ranaut', 'Madhavan'],
 ['Madhavan', 'Ritika Singh'],
 ['Joseph Vijay', 'Samantha Ruth Prabhu'],
 ['Ranbir Kapoor', 'Konkona Sen Sharma'],
 ['Deepika Padukone', 'Amitabh Bachchan'],
 ['Mahesh Babu', 'Kriti Sanon'],
 ['Shah Rukh Khan', 'Kajol'],
 ['Ranbir Kapoor', 'Paresh Rawal'],
 ['Ram Charan', 'Arvind Swamy'],
 ['Imran Khan', 'Vir Das'],
 ['Ajith Kumar', 'Shraddha Srinath'],
 ['Pankaj Tripathi', 'Abhishek Bachchan'],
 ['Hrithik Roshan', 'Aishwarya Rai Bachchan'],
 ['Rajkummar Rao', 'Shraddha Kapoor'],
 ['Shah Rukh Khan', 'Aishwarya Rai Bachchan'],
 ['John Abraham', 'Boman Irani'],
 ['Kunal Khemu', 'Rasika Dugal'],
 ['Dhanush', 'Sonam Kapoor'],
 ['Rajkummar Rao', 'Geetanjali Thapa'],
 ['Shah Rukh Khan', 'Manisha Koirala'],
 ['Saif Ali Khan', 'Urmila Matondkar'],
 ['Ranbir Kapoor', 'Prem Chopra'],
 ['Vijay Deverakonda', 'Rashmika Mandanna'],
 ['Harshvardhan Kapoor', 'Priyanshu Painyuli'],
 ['Akshaye Khanna', 'Aftab Shivdasani'],
 ['Irrfan Khan', 'Jimmy Sheirgill'],
 ['Madhavan', 'Saif Ali Khan'],
 ['Arshad Warsi', 'Amrita Rao'],
 ['Rishi Kapoor', 'Neetu Singh'],
 ['Rana Daggubati', 'Kay Kay Menon'],
 ['Joseph Vijay', 'Trisha Krishnan'],
 ['Antony Varghese', 'Chemban Vinod Jose'],
 ['Irrfan Khan', 'Dulquer Salmaan'],
 ['Ayushmann Khurrana', 'Kriti Sanon'],
 ['Suriya', 'Asin Thottumkal'],
 ['Aamir Khan', 'Juhi Chawla'],
 ['Rajat Kapoor', 'Neha Dhupia'],
 ['Priyanka Chopra', 'Farhan Akhtar'],
 ['Ayushmann Khurrana', 'Bhumi Pednekar'],
 ['Rajinikanth', 'Shriya Saran']]

print(len(a))
